### ISSUE TITLE
README.md instructions for "How to use" are incorrect (suggestion enclosed)

### ISSUE THREAD

**Issue by texadactyl** [smirik/mercury#22]
And, it recently caused an unnecessary bug report (#21).

Set up for running a model:
1. Initialize the *.in files from the samples: ```make gen-in```
2. Edit the *.inc and *.in files as needed for the model at hand (your application).
3. Remove any existing old generated files (E.g. results of previous execution): ```make rm-gen```
4. Un-build the Fortran programs: ```make unbuild```
5. Build the Fortran programs: ```make build```
6. Make sure that there are no compilation errors in the previous step.

Now, you are ready to run your model.  Three steps:

1. ```mercury6```
2. ```element6```
3. ```close6```

Simplistic, perhaps.  But, a rough outline at least.
Feedback?

**Comment by smirik** [comment]
It seems that I've missed a lot of notifications from GitHub about the issues and PRs... Sorry for that.

Do you think it is still relevant to add some adjustments to the README.file with the workflow you have described? While your recent PR addresses many possible questions, it might be a good idea to mention explicitly the minimal example.

**Comment by texadactyl** [comment]
@smirik 
Evolution sometimes breeds irrelevancy.
