### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by dahlend** [smirik/mercury#26]
Hi,
I am interested in using these tools, but they don't seem to have any software license.

Would you consider adding a license such as the MIT open source license or similar?
https://opensource.org/licenses/MIT

Without a license, this technically shouldn't be used without explicit permission from the authors.

Thanks

**Comment by texadactyl** [comment]
Added this to PR #28.

**Comment by texadactyl** [comment]
@smirik 
I understand.
The GNU license was chosen because it is open and their Fortran (gfortran) is used for all of the source code.
An MIT or Apache or other licenses would be okay too.
Also, one could write up a custom license.
Peace.

**Comment by smirik** [comment]
I'm good with GPL. While it is not MIT, I do not expect any issues because of that. Btw, thank you for adding the licence file :)
